apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: windows-iso-cloner
  namespace: kvm
rules:
  # CDI требует право 'create' на ресурс 'datavolumes/source' в исходном namespace для клонирования
  - apiGroups: ["cdi.kubevirt.io"]
    resources: ["datavolumes/source"]
    verbs: ["create"]
  # Права на чтение конкретных DataVolumes
  - apiGroups: ["cdi.kubevirt.io"]
    resources: ["datavolumes"]
    verbs: ["get"]
    resourceNames: ["windows-10-iso", "windows-10-golden-image"]
  # Права на чтение соответствующих PVC
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get"]
    resourceNames: ["windows-10-iso", "windows-10-golden-image"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: windows-iso-cloner-binding
  namespace: kvm
subjects:
  # Даем доступ всем ServiceAccounts кластера (чтобы работало для всех namesapces пользователей: kv-user1, kv-user2 и т.д.)
  - kind: Group
    name: system:serviceaccounts
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: windows-iso-cloner
  apiGroup: rbac.authorization.k8s.io
