apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubevirt-manager-monitor
  namespace: kvm
  labels:
    app: kubevirt-api-manager
spec:
  selector:
    matchLabels:
      app: kubevirt-api-manager
  endpoints:
  - port: http
    interval: 30s
  namespaceSelector:
    matchNames:
    - kvm
